from SCons.Script import Default, Glob, SConscript

# Use godot-cpp's SConstruct to configure the environment.
env = SConscript("../godot-cpp/SConstruct")

# Include shared headers (sim_state.h)
env.Append(CPPPATH=[
    "#",
    "#/../../../",
])

sources = Glob("src/*.cpp")
target = "bin/libgenesis_bridge{}{}".format(env["suffix"], env["SHLIBSUFFIX"])
library = env.SharedLibrary(target=target, source=sources)
env.NoCache(library)
Default(library)
