# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: perception.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'perception.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10perception.proto\x12\x0ekim.perception\"\x7f\n\nAudioChunk\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x11\n\tpcm_s16le\x18\x03 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x05 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\"s\n\nAudioEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08start_ms\x18\x04 \x01(\x05\x12\x0e\n\x06\x65nd_ms\x18\x05 \x01(\x05\x12\x0e\n\x06source\x18\x06 \x01(\t\"R\n\x10\x41udioEventsReply\x12*\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1a.kim.perception.AudioEvent\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\"V\n\x0bHealthReply\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nlatency_ms\x18\x03 \x01(\x05\x12\x12\n\nlast_error\x18\x04 \x01(\t2\xa6\x01\n\x0f\x41udioPerception\x12M\n\rClassifyChunk\x12\x1a.kim.perception.AudioChunk\x1a .kim.perception.AudioEventsReply\x12\x44\n\x06Health\x12\x1d.kim.perception.HealthRequest\x1a\x1b.kim.perception.HealthReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perception_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=36
  _globals['_AUDIOCHUNK']._serialized_end=163
  _globals['_AUDIOEVENT']._serialized_start=165
  _globals['_AUDIOEVENT']._serialized_end=280
  _globals['_AUDIOEVENTSREPLY']._serialized_start=282
  _globals['_AUDIOEVENTSREPLY']._serialized_end=364
  _globals['_HEALTHREQUEST']._serialized_start=366
  _globals['_HEALTHREQUEST']._serialized_end=381
  _globals['_HEALTHREPLY']._serialized_start=383
  _globals['_HEALTHREPLY']._serialized_end=469
  _globals['_AUDIOPERCEPTION']._serialized_start=472
  _globals['_AUDIOPERCEPTION']._serialized_end=638
# @@protoc_insertion_point(module_scope)
